# Site settings
title: alexandrius's blog
author: Alexander Pataridze
author_avatar: /images/logo.png
email: me@alexandrius.com
description: Android development and stuff.
#baseurl: "http://alexandrius.com" # optional
url: "https://alexandrius.com"
#twitter_username: foo_bar
github_username: alexandrius
#github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap